spring.application.name=customer-service
server.port=8081
spring.data.rest.base-path=/api
spring.datasource.url=jdbc:h2:mem:customer-service-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
customer.params.x=10
customer.params.y=20
global.params.p1=default-p1
global.params.p2=default-p2
spring.cloud.config.enabled=false
spring.cloud.discovery.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
spring.config.import=optional:configserver:http://localhost:9999



