spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:4200
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: customers
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customers/**
        - id: inventory
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/products/**
        - id: billing
          uri: lb://BILLING-SERVICE
          predicates:
            - Path=/api/bills/**

